### ISSUE TITLE
 key param cannot be coerced into a private key

### ISSUE THREAD

**Issue by ghost** [aerialship/lightsaml#10]
Warning: openssl_sign(): supplied key param cannot be coerced into a private key in vendor\rnijveld\xmlseclibs\xmlseclibs.php line 502
at vendor\rnijveld\xmlseclibs\xmlseclibs.php line 502 

Happens due to formatter certificate, when trimmed to one line, it works fine

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<EntityDescriptor entityID="http://meere.internal.forgerock.com:8080/OpenAM" xmlns="urn:oasis:names:tc:SAML:2.0:metadata">
    <IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <KeyDescriptor use="signing">
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>
MIICQDCCAakCBEeNB0swDQYJKoZIhvcNAQEEBQAwZzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNh
bGlmb3JuaWExFDASBgNVBAcTC1NhbnRhIENsYXJhMQwwCgYDVQQKEwNTdW4xEDAOBgNVBAsTB09w
ZW5TU08xDTALBgNVBAMTBHRlc3QwHhcNMDgwMTE1MTkxOTM5WhcNMTgwMTEyMTkxOTM5WjBnMQsw
CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEUMBIGA1UEBxMLU2FudGEgQ2xhcmExDDAK
BgNVBAoTA1N1bjEQMA4GA1UECxMHT3BlblNTTzENMAsGA1UEAxMEdGVzdDCBnzANBgkqhkiG9w0B
AQEFAAOBjQAwgYkCgYEArSQc/U75GB2AtKhbGS5piiLkmJzqEsp64rDxbMJ+xDrye0EN/q1U5Of+
RkDsaN/igkAvV1cuXEgTL6RlafFPcUX7QxDhZBhsYF9pbwtMzi4A4su9hnxIhURebGEmxKW9qJNY
Js0Vo5+IgjxuEWnjnnVgHTs1+mq5QYTA7E6ZyL8CAwEAATANBgkqhkiG9w0BAQQFAAOBgQB3Pw/U
QzPKTPTYi9upbFXlrAKMwtFf2OW4yvGWWvlcwcNSZJmTJ8ARvVYOMEVNbsT4OFcfu2/PeYoAdiDA
cGy/F2Zuj8XJJpuQRSE6PtQqBuDEHjjmOQJ0rV/r8mO1ZCtHRhpZ5zYRjhRC9eCbjx9VrFax0JDC
/FfwWigmrW0Y0Q==
                    </ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </KeyDescriptor>
        <ArtifactResolutionService index="0" isDefault="true" Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="http://meere.internal.forgerock.com:8080/OpenAM/ArtifactResolver/metaAlias/idp"/>
        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://meere.internal.forgerock.com:8080/OpenAM/IDPSloRedirect/metaAlias/idp" ResponseLocation="http://meere.internal.forgerock.com:8080/OpenAM/IDPSloRedirect/metaAlias/idp"/>
        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://meere.internal.forgerock.com:8080/OpenAM/IDPSloPOST/metaAlias/idp" ResponseLocation="http://meere.internal.forgerock.com:8080/OpenAM/IDPSloPOST/metaAlias/idp"/>
        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="http://meere.internal.forgerock.com:8080/OpenAM/IDPSloSoap/metaAlias/idp"/>
        <ManageNameIDService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://meere.internal.forgerock.com:8080/OpenAM/IDPMniRedirect/metaAlias/idp" ResponseLocation="http://meere.internal.forgerock.com:8080/OpenAM/IDPMniRedirect/metaAlias/idp"/>
        <ManageNameIDService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://meere.internal.forgerock.com:8080/OpenAM/IDPMniPOST/metaAlias/idp" ResponseLocation="http://meere.internal.forgerock.com:8080/OpenAM/IDPMniPOST/metaAlias/idp"/>
        <ManageNameIDService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="http://meere.internal.forgerock.com:8080/OpenAM/IDPMniSoap/metaAlias/idp"/>
        <NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</NameIDFormat>
        <NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</NameIDFormat>
        <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
        <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</NameIDFormat>
        <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:WindowsDomainQualifiedName</NameIDFormat>
        <NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:kerberos</NameIDFormat>
        <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName</NameIDFormat>
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://meere.internal.forgerock.com:8080/OpenAM/SSORedirect/metaAlias/idp"/>
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://meere.internal.forgerock.com:8080/OpenAM/SSOPOST/metaAlias/idp"/>
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="http://meere.internal.forgerock.com:8080/OpenAM/SSOSoap/metaAlias/idp"/>
        <NameIDMappingService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="http://meere.internal.forgerock.com:8080/OpenAM/NIMSoap/metaAlias/idp"/>
        <AssertionIDRequestService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="http://meere.internal.forgerock.com:8080/OpenAM/AIDReqSoap/IDPRole/metaAlias/idp"/>
        <AssertionIDRequestService Binding="urn:oasis:names:tc:SAML:2.0:bindings:URI" Location="http://meere.internal.forgerock.com:8080/OpenAM/AIDReqUri/IDPRole/metaAlias/idp"/>
    </IDPSSODescriptor>
</EntityDescriptor>
```

**Comment by ghost** [comment]
Hello, 

I have the same problem 
`PHP Warning:  openssl_sign(): supplied key param cannot be coerced into a private key in /path/to/project/vendor/rnijveld/xmlseclibs/xmlseclibs.php on line 502`

My cert files were made with this command from [this documentation](https://github.com/aerialship/lightsaml/blob/master/doc/signing_and_certificates.md) 
`openssl req -new -x509 -days 3652 -nodes -out saml.crt -keyout saml.pem`

My security config follows [this documentation](https://github.com/aerialship/SamlSPBundle/blob/master/src/AerialShip/SamlSPBundle/Resources/doc/configuration.md) : 

```
    firewalls:
        saml:
            pattern: ^/
            anonymous: true
            aerial_ship_saml_sp:
                login_path: /saml/sp/login
                check_path: /saml/sp/acs
                logout_path: /saml/sp/logout
                failure_path: /saml/sp/failure
                metadata_path: /saml/sp/sp-FederationMetadata.xml
                discovery_path: /saml/sp/discovery
                local_logout_path: /logout
                default_target_path: /
                provider: in_memory
                create_user_if_not_exists: false
                services:
                    somename:
                        idp:
                            file: "%kernel.root_dir%/../src/AppBundle/Resources/public/FederationMetadata.xml"
                       sp:
                            config:
                                entity_id: http://my.adfs.company.com
                            signing:
                                cert_file: "%kernel.root_dir%/../src/AppBundle/Resources/public/saml.crt"
                                key_file: "%kernel.root_dir%/../src/AppBundle/Resources/public/saml.pem"
                                key_pass: ""
                            meta:
                                name_id_format: persistent
                                binding:
                                    # any saml binding or shortcuts: post or redirect
                                    authn_request: redirect
                                    response: post
                                    logout_request: redirect
            logout:
                path: /logout
```

Could you help me to fix this openssl error ?
