### ISSUE TITLE
AuthnRequest send and Response receive bidnings and url

### ISSUE THREAD

**Issue by tmilos** [aerialship/lightsaml#20]
Related to  aerialship/SamlSPBundle#24 
## Case 1

``` yaml
IDP:
    SSO:
        binding: A
        url: sso1
SP:
    ACS:
        binding: B
        url: acs1
spMeta: ~

AuthnRequest:
    sent:
        binding: A
        url: sso1
    content:
        acsURL: acs1
        binding: B
```
## Case 2

``` yaml
IDP:
    SSO:
        binding: A
        url: sso1
    SSO:
        binding: B
        url: sso2
SP:
    ACS:
        binding: C
        url: acs1
    ACS:
        binding: D
        url: acs2
spMeta: ~

AuthnRequest:
    sent:
        binding: A
        url: sso1
    content:
        acsURL: acs1
        binding: C
```
## Case 3

``` yaml
IDP:
    SSO:
        binding: A
        url: sso1
    SSO:
        binding: B
        url: sso2
SP:
    ACS:
        binding: C
        url: acs1
    ACS:
        binding: D
        url: acs2
spMeta: 
    authnRequestBinding: B
    responseBinding: D

AuthnRequest:
    sent:
        binding: B
        url: sso2
    content:
        acsURL: acs2
        binding: D
```
## Case 4

``` yaml
IDP:
    SSO:
        binding: A
        url: sso1
    SSO:
        binding: B
        url: sso2
SP:
    ACS:
        binding: C
        url: acs1
    ACS:
        binding: D
        url: acs2
spMeta: 
    authnRequestBinding: X

Exception:
    IDP does not have SSO with binding X
```
## Case 5

``` yaml
IDP:
    SSO:
        binding: A
        url: sso1
    SSO:
        binding: B
        url: sso2
SP:
    ACS:
        binding: C
        url: acs1
    ACS:
        binding: D
        url: acs2
spMeta: 
    responseBinding: X

Exception:
    SP does not have ACS with binding X
```
